# Generated by Django 3.0.6 on 2020-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll', models.IntegerField()),
                ('dpartment', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('blood_group', models.CharField(max_length=100)),
            ],
        ),
    ]
